server:
  port: 7001
  
spring:
  application:
    name: jeecg-system
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
#        username: @config.username@
#        password: @config.password@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
#        username: @config.username@
#        password: @config.password@
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-dev.yaml